### PR TITLE
added fixed size to resolve touchscreen resize

### PR DESCRIPTION
**Pull request by Justin-Hung**
Still need to test with the pi but I believe the setFixedSize() function should do the trick.

### CODE REVIEW

**Comment by bill-luu** [comment]
Is this addressing #33, or a different issue?

**Comment by Justin-Hung** [comment]
Yea this address's issue #33

**Comment by bill-luu** [comment]
Cool! We'll need the Pi to confirm. @Reddragoneer1 can set you up with it.

**Comment by nathanaelhuh** [comment]
Sure, I'll do this on Thursday

**Review by nathanaelhuh — APPROVED** [review]

**Pull request merged**
